
--load using snowpipe
CREATE OR REPLACE SCHEMA SPOTIFY_AIRFLOW.PIPES;

CREATE OR REPLACE PIPE SPOTIFY_AIRFLOW.PIPES.album_pipe
AUTO_INGEST = TRUE
AS
COPY INTO SPOTIFY_AIRFLOW.SPOTIFY_AIRFLOW_SCHEMA.tblalbum
FROM @SPOTIFY_AIRFLOW.EXTERNAL_STAGES.ALBUM_EXT_STAGE
FILE_FORMAT = SPOTIFY_AIRFLOW.FILE_FORMATS.CSV;

DESC PIPE album_pipe;

SELECT COUNT(*) FROM SPOTIFY_AIRFLOW.SPOTIFY_AIRFLOW_SCHEMA.tblalbum;

-----

CREATE OR REPLACE PIPE SPOTIFY_AIRFLOW.PIPES.artist_pipe
AUTO_INGEST = TRUE
AS
COPY INTO SPOTIFY_AIRFLOW.SPOTIFY_AIRFLOW_SCHEMA.tblArtist
FROM @SPOTIFY_AIRFLOW.EXTERNAL_STAGES.ARTIST_EXT_STAGE
FILE_FORMAT = SPOTIFY_AIRFLOW.FILE_FORMATS.CSV;

DESC PIPE SPOTIFY_AIRFLOW.PIPES.artist_pipe;


SELECT COUNT(*) FROM SPOTIFY_AIRFLOW.SPOTIFY_AIRFLOW_SCHEMA.tblArtist;

--------
CREATE OR REPLACE PIPE SPOTIFY_AIRFLOW.PIPES.song_pipe
AUTO_INGEST = TRUE
AS
COPY INTO SPOTIFY_AIRFLOW.SPOTIFY_AIRFLOW_SCHEMA.tblSongs
FROM @SPOTIFY_AIRFLOW.EXTERNAL_STAGES.SONG_EXT_STAGE
FILE_FORMAT = SPOTIFY_AIRFLOW.FILE_FORMATS.CSV;

DESC PIPE SPOTIFY_AIRFLOW.PIPES.song_pipe;

SELECT COUNT(*) FROM SPOTIFY_AIRFLOW.SPOTIFY_AIRFLOW_SCHEMA.tblSongs;


